# Copyright (C) Eta Scale AB. Licensed under the Eta Scale Open Source License. See the LICENSE file for details.

######
# Setting the targets to build
# 

# Targets to build
INDIR_COUNT=4
GRAN_COUNT=2

ORIGINAL_SUFFIX=original
CAE_SUFFIX=cae
DAE_TYPE=dae
ARGS_SUFFIX=pref-arg
TM_SUFFIX=tm-dae

# Targets
ORIGINAL_TARGETS=$(BENCHMARK).$(ORIGINAL_SUFFIX)
DAE_TARGETS=$(foreach type, $(DAE_TYPE), \
		 $(foreach indir, $(INDIR_COUNT), \
			$(foreach gran, $(GRAN_COUNT), \
				$(BENCHMARK).gran$(gran).indir$(indir).$(type))))

CAE_TARGETS=$(foreach indir, $(INDIR_COUNT), $(BENCHMARK).gran$(indir).$(CAE_SUFFIX))

TM_TARGETS=$(foreach indir, $(INDIR_COUNT), \
			$(foreach gran, $(GRAN_COUNT),   \
				$(BENCHMARK).tm-gran$(gran).tm-indir$(indir).$(TM_SUFFIX)))


ALLTARGETS=$(DAE_TARGETS) $(CAE_TARGETS) $(ORIGINAL_TARGETS) 

ALLTARGETS=$(TM_TARGETS) $(ORIGINAL_TARGETS)

# Output directory
BINDIR=../bin

# TARGETS
TARGETS=$(addprefix $(BINDIR)/, $(ALLTARGETS))



