#ifndef ANNOTATED_REGIONS_H
#define ANNOTATED_REGIONS_H

#define REGION_ENTRY 1
#define REGION_EXIT 0

typedef enum AnnotatedRegion {
  REG_DAE_ACCESS_PREFETCH = 0,
  REG_BARRIER,
  REG_ABORT_HANDLER_BACKOFF,
  REG_ABORT_HANDLER_ACQLOCK,
  REG_ABORT_HANDLER_HASLOCK,
  REG_ABORT_HANDLER_FAULTTOUCHMEM,
  NUM_ANNOTATED_REGIONS
} AnnotatedRegion_t;

#endif
