# Makefile for the first pass

# Path to top level of LLVM hierarchy
LEVEL = ../../../../build/llvm-build

# Name of the library to build
LIBRARYNAME = TMFKernelPrefetch

# Make the shared library become a loadable module so the tools can
# dlopen/dlsym on the resulting library.
LOADABLE_MODULE = 1

# Include the makefile implementation stuff
include $(LEVEL)/Makefile.common