# Copyright (C) Eta Scale AB. Licensed under the Eta Scale Open Source License. See the LICENSE file for details.

######
# Setting the environment variables 
#

COMPILER_LIB=$(HOME)/Documents/daedal/compiler/build/projects-build/lib
LLVM_BIN=$(HOME)/Documents/daedal/compiler/build/llvm-build/bin/