BENCHMARK = $(PROG)

LIB_LLS := ${SRCS_LIBS:.c=.ll}

LIB_OBJS := $(LIB_GEM5)/m5op_x86.o \
            $(LIB_GEM5)/m5ops_wrapper.o \
            $(LIB_PERF)/perf_counters.o \

include $(LEVEL)/common/DAE/Makefile.targets
include $(LEVEL)/common/DAE/Makefile.defaults

